---
# irods/tasks/main.yml

- name: Make dl_dir
  file:
    path: "{{ dl_dir }}"
    state: directory

- name: Install iRODS role prereqs
  apt:
    name={{ item }}
    update_cache=yes
    cache_valid_time=3600
    state=installed
  with_items:
    - git
    - postgresql-9.3
    - python-pika
    - python-psycopg2
    - uuid-dev

- name: Download iRODS packages
  get_url:
    url: "{{ item.url }}"
    checksum: "{{ item.cksum }}"
    dest: "{{ dl_dir }}/{{ item.url | basename }}"
  with_items: "{{ irods_packages }}"

- name: Install iRODS packages
  apt:
    deb: "{{ dl_dir }}/{{ item.url | basename  }}"
    state: installed
  with_items: "{{ irods_packages }}"

- name: add iRODS database
  become_user: postgres
  postgresql_db:
    name: "{{ irods_db_name }}"

- name: add iRODS admin user to postgres
  become_user: postgres
  postgresql_user:
    db: "{{ irods_db_name }}"
    priv: ALL
    name: "{{ irods_db_user }}"
    password: "{{ irods_db_password }}"

- name: copy over reConfile rule files
  template:
    src: "reConfigs/{{ item }}.j2"
    dest: "/var/lib/irods/iRODS/server/config/reConfigs/{{ item }}"
  with_items:
    - ipc-amqp.re
    - ipc-custom.re
    - ipc-env.re
    - ipc-json.re
    - ipc-logic.re
    - ipc-uuid.re

- name: clone Cyverse iRODS repos
  git:
    repo: "{{ item }}"
    dest: "{{ dl_dir }}/{{ item | basename }}"
    version: master
  with_items:
    - "https://github.com/cyverse/irods-setavu-mod"
    - "https://github.com/cyverse/irods-cmd-scripts"

- name: Make iRODS modules directory
  file:
    path: "/var/lib/irods/iRODS/modules/"
    state: directory

- name: install Cyverse setAVU module
  command: "cp -r {{ dl_dir }}/irods-setavu-mod /var/lib/irods/iRODS/modules/setavu"
  args:
    creates: "/var/lib/irods/iRODS/modules/setavu"

- name: install Cyverse command scripts
  command: "cp -r {{ dl_dir }}/irods-cmd-scripts/{{ item }} /var/lib/irods/iRODS/server/bin/cmd/{{ item }}"
  args:
    creates: "/var/lib/irods/iRODS/server/bin/cmd/{{ item }}"
  with_items:
    - "amqptopicsend.py"
    - "generateuuid.sh"

- name: Create iRODS configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ dl_dir }}/{{ item }}"
  with_items:
    - setup_icommands
    - setup_irods

- name: Configure iRODS service
  when:
  command: "/var/lib/irods/packaging/setup_irods.sh < {{ dl_dir }}/setup_irods"

- name: Configure iCommands for administration
  when:
  command: "iinit < {{ dl_dir }}/setup_irods"



