---
# file: roles/docker-demo/tasks/main.yml

# Use docker build with a Dockerfile so we can build a 
# custom docker image (in this case, includes python
# since python is required for the docker module)

- name: Check for existing docker images
  command: docker images
  register: docker_images

- name: Check for running docker images
  command: docker ps -a --filter=status=running
  register: docker_running
  when: docker_images.stdout.find("demo") != -1
  
- set_fact:
    packages: "{{ irods3_packages }}"
  when: "{{ docker_preload_packages | bool }} and {{ irods_version | int }} == 3"

- set_fact:
    packages: "{{ irods4_packages }}"
  when: "{{ docker_preload_packages | bool }} and {{ irods_version | int }} == 4"

- name: Build docker host images
  command: "docker build --build-arg preload_packages={{ packages | default('') }} -t {{ inventory_hostname }} ./roles/docker-demo/files/"
  when: docker_images.stdout.find("demo") == -1

- name: Run docker hosts
  docker:
    image: "{{ inventory_hostname }}"
    name: "{{ inventory_hostname }}"
    state: reloaded
    use_tls: "encrypt"
    publish_all_ports: yes
    command: "sleep {{ docker_container_uptime }}"
  when: docker_running.changed == false or docker_running.stdout.find("demo") == -1
