---
# playbook for jenkins installation

- hosts: all
  become: yes
  roles:
    - common-prep
    - ssh-lockdown
    - ufw
    - apt-cacher-ng
    - apache
    - jenkins
    - jenkins-debian-glue
    - docker

