---
# file: roles/common-prep/tasks/main.yml

- name: Upgrade system to current using apt
  apt:
    upgrade=dist
    update_cache=yes
    cache_valid_time=3600

- name: Install standard packages
  apt: pkg={{ item }} state=present
  with_items:
   - tmux
   - vim

- name: Install additional packages
  apt: pkg={{ item }} state=present
  with_items: "{{ additional_debian_packages }}"

- stat:
    path=/var/run/reboot-required
  register: reboot-required

- name: Reboot if required
  when: reboot-required.stat.exists is defined
  debug: msg="System will reboot"
  notify:
    - restart host
    - wait for host

- name: Enable vim syntax highlighting
  lineinfile: dest=/etc/vim/vimrc
    regexp="^\s*syntax on"
    line="syntax on"

- name: Remove nano
  apt:  pkg={{ item }} state=absent
  with_items:
   - nano

