---
# syndicate-ug-http/tasks/main.yml
# Installs syndicate-ug-http packages

- name: Utilities
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: installed
  with_items:
    - curl
    - daemon
    - make
    - unzip

- name: SSL support for apt
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: installed
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Trust butler opencloud apt repo
  apt_key:
    data: "{{ lookup('file', 'butler_opencloud_cs_arizona_edu_pub.gpg') }}"
    state: present

- name: Copy butler SSL key
  copy:
    src: butler.crt
    dest: /usr/local/share/ca-certificates
  register: ssl_key_added

- name: Trust SSL key
  when: ssl_key_added.changed
  command: "update-ca-certificates"

- name: Add apt repo for syndicate packages
  apt_repository:
    repo: "deb https://butler.opencloud.cs.arizona.edu/repos/release/syndicate syndicate main"
    filename: "butler"
    state: present

- name: Create syndicate user
  user:
    name: "{{ syndicate_user }}"
    password: "{{ syndicate_password | password_hash('sha512') }}"
    shell: /bin/bash

- name: Add syndicate user to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ syndicate_user }}"
    line: "%{{ syndicate_user }} ALL=(ALL) NOPASSWD: ALL"

- name: Copy syndicate user startup and env configuration
  copy:
    src: "{{ item }}"
    dest: "/home/{{ syndicate_user }}"
    owner: "syndicate"
    group: "syndicate"
    mode: "0755"
  with_items:
    - .inputrc
    - .vimrc
