---
# syndicate/tasks/main.yml
# Installs syndicate packages

- name: Trust butler opencloud apt repo
  apt_key:
    data: "{{ lookup('file', 'butler_opencloud_cs_arizona_edu_pub.gpg') }}"
    state: present

- name: Copy butler SSL key
  copy:
    src: butler.crt
    dest: /usr/local/share/ca-certificates
  register: ssl_key_added

- name: Trust SSL key
  when: ssl_key_added.changed
  command: "update-ca-certificates"

- name: Enable apt over https
  apt:
    name: apt-transport-https
    update_cache: yes
    cache_valid_time: 3600
    state: installed

- name: Add apt repo for syndicate packages
  apt_repository:
    repo: "deb https://butler.opencloud.cs.arizona.edu/repos/release/syndicate syndicate main"
    filename: "butler"
    state: present

- name: Install syndicate packages
  apt:
    name: apt-transport-https
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  with_items:
    - syndicate-core
    - syndicate-ug-tools
    - syndicate-rg
    - syndicate-ag
    - syndicatefs

