---
# syndicate/tasks/main.yml
# Installs syndicate packages

- name: Install syndicate packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
    - syndicate-core
    - syndicate-ug-tools
    - syndicate-rg
    - syndicate-ag
    - syndicatefs
    - syndicate-fs-driver
